# Basic Information 
title: Mingni Tang
position: Ph.D. Student
affiliation: The Hong Kong Polytechnic University (PolyU)
affiliation_link: https://www.polyu.edu.hk/
#change
#affiliation_logo: ./assets/img/university-logo-small-horizontal-white-156eae9527.svg
email: minnie17.tang@connect.polyu.hk

# Search Engine Optimization (SEO)
keywords: mingni tang, tang mingni, mingnitang, tangmingni, tangmn, minnie,minnie-tang, minnie tang, youth safety, music , LLM
canonical: https://mingnitang.github.io/
description: Mingni Tang is a Ph.D. student at The Hong Kong Polytechnic University (PolyU). Her research lies in natural language processing, large language models, multimodal music understanding, and social impact.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
#change
link_type: text #text/icon
google_scholar:
#change
cv_link: ./assets/pdf/Resume_of_minnie.pdf
github_link:

linkedin: 
twitter: 

# Images 
#change
avatar: ./assets/img/mingni-profile-original.JPG
#favicon: ./assets/img/favicon.png
#favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
#footnote: Feel free to use my website's source code.
#footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.

#clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
